name: "say-hello"
description: "Returns a greeting output with a greeting to the input name"
inputs:
  name:
    description: Name
    required: true
outputs:
  greeting:
    description: Greeting
    value: ${{ steps.say-hello.outputs.greeting }}
runs:
  using: "composite"
  steps:
    - name: say-hello
      shell: bash
      env:
        INPUT_NAME: ${{ inputs.name }}
      run: |
        GREETING="Hello $INPUT_NAME"
        echo "greeting=$GREETING" >> $GITHUB_OUTPUT
