name: Greetings
on: [workflow_dispatch]
jobs:
  aggregate_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2

      - name: Call Composite Action hello-from
        uses: ./.github/actions/first_action
        id: hello-from
        with:
          action-number: "First"

      - name: Call Composite Action say-hello
        uses: ./.github/actions/second_action
        id: say-hello
        with:
          name: Caio

      - name: echo output from say-hello
        run: |
          echo ${{ steps.say-hello.outputs.greeting }}

      - name: Call Composite Action hello-from
        uses: ./.github/actions/first_action
        id: hello-from-third
        with:
          action-number: "Third"
